#!/bin/sh
set -e

RUNDIR=/var/run/elasticsearch
PIDFILE=$RUNDIR/elasticsearch.pid

mkdir -p $RUNDIR
touch $PIDFILE
#chown redis:redis $RUNDIR $PIDFILE
chmod 755 $RUNDIR

#chown -R redis:redis /data
#chmod -R 700 /data

#chown -R redis:redis /var/log/redis

exec chpst -u root /elasticsearch/bin/elasticsearch
